### ISSUE TITLE
Meaning first Spock Question

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana-questionnaire#1]
I think the first Spock question is not clear:

""Would you prefer to have Python based syntax to execute macros e.g. mv('mot01', 100) instead of mv mot01 100? ""

what is really meant?, if you want to have it instead of the existing one (this is what I would understand from the question) or if you want to have it in addition (this is what I would understand from the suggested answers)?. I would say that either the question has to be formulated in other way or the answers have to be changed.

**Comment by reszelaz** [comment]
Thanks for the comment! And for reviewing the questionnaire.

This question is about exclusive preference. If finally we open this development I would not go for a mixed implementations. So, there would be eventually two syntaxes: spock and python and the user would need to choose one for using Spock. Based on the questionnaire results we could eventually prioritize development of new _python based syntax_ (or whatever this implies) instead of fixing bugs in the old one. 

Now the question is:

```
    item = "Would you prefer to have Python based syntax to execute macros e.g. mv('mot01', 100) instead of mv mot01 100?";
    var choices = ["Yes",
        "Not now but I may use it in the future",
        "Not now and I doubt I will use it in the future",
        "No and this feature does not have sense to me"];
```

We could make it more explicit:

```
    item = "Would you prefer to have Python based syntax to execute macros e.g. mv('mot01', 100) instead of spock syntax mv mot01 100?";
    var choices = ["Yes, I would directly switch to it whenever available",
        "If available I would still use the spock syntax but maybe at some point in the future I would switch to the python based syntax.",
        "No, I think I would stick to the spock syntax even if the python based syntax was available",
        "No and this feature does not have sense to me"];
```

My idea is to have, similarly to other questions, 4 possible answers: 2 possitive (one strong and the other weak) and 2 negative (one strong and one weak).

**Comment by teresanunez** [comment]
Thanks for the explanation. I completely agree with your new suggestions for the answers, many
thanks.
